In [14]:
####Task 1 : Making dataframeworks and storing them as .csv####

# Importing the panda library
import pandas as pd
# Importing the numpy library
import numpy as np

# Creating a dictionary for employee
employee_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'], # Unique identifier strings for employees
    'Name': ['John Alter', 'Alice Luxumberg', 'Tom Sabestine', 'Nina Adgra', 'Amy Johny'], # Full names
    'Gender': ['M', 'F', 'M', 'F', 'F'], # Gender indicators where M is Male and F is Female
    'City': ['Paris', 'London', 'Berlin', 'Newyork', 'Madrid'], # Geographic office locations
    'Age': [25, 27, 29, 31, 30] # Age values represented as integers
}

# Converting the employee dictionary into a standard pandas DataFrame object
employee_df = pd.DataFrame(employee_data)

# Saving the created employee dataframe as a comma-separated file named employee.csv without indexing
employee_df.to_csv('employee.csv', index=False)

# Creating a dictionary mapping each employee ID to their corporate ranking level
seniority_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'], # Matching employee ID strings
    'Designation Level': [2, 2, 3, 2, 3] # Designation ranks
}

# Convert the seniority ranking dictionary into a standard pandas DataFrame object
seniority_df = pd.DataFrame(seniority_data)

# Saving the seniority dataframe as a separate comma-separated file named seniority.csv without indexing
seniority_df.to_csv('seniority.csv', index=False)

# Creating a multi-row dictionary containing project details, tracker milestones, and budgets
project_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005', 'A002', 'A005', 'A003', 'A001', 'A003', 'A001', 'A004', 'A004', 'A005'], # Associated owner IDs
    'Project': ['Project 1', 'Project 2', 'Project 3', 'Project 4', 'Project 5', 'Project 6', 'Project 7', 'Project 8', 'Project 9', 'Project 10', 'Project 11', 'Project 12', 'Project 13', 'Project 14'], # Code names
    'Cost': [1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 350000, np.nan, 300000, 2000000, 1000000, 3000000, 2000000], # Budgets with missing markers
    'Status': ['Finished', 'Ongoing', 'Finished', 'Ongoing', 'Finished', 'Failed', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Finished'] # Operations milestones
}

# Converting the compiled operational projects dictionary into a standard pandas DataFrame object
project_df = pd.DataFrame(project_data)

# Save the project dataframe out to a target comma-separated file named project.csv without adding indexing rows
project_df.to_csv('project.csv', index=False)

# Displaying the all dataframes directly in the notebook output
print(employee_df)
print(seniority_df)
print(project_df)

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30
     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3
      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14  2000000.0  Finished

In [15]:
####Task 2: Replacing missing cost values by running average using for loop####
# Importing numpy
import numpy as np

# Loading the project dataset created in Task 1
project_df = pd.read_csv('project.csv')

# Initializing tracking variables to calculate the running average manually
total_cost_sum = 0.0
valid_cost_count = 0

# Looping through each row index of the dataframe using its length
for index in range(len(project_df)):
    # Retrieve the cost value for the current row using .at
    current_cost = project_df.at[index, 'Cost']
    
    # Checking if cost is missing
    if np.isnan(current_cost):
        # If no valid numbers has been found, default the average to 0
        if valid_cost_count == 0:
            running_avg = 0.0
        else:
            # Calculating the running average from the accumulated sum and count
            running_avg = total_cost_sum / valid_cost_count
        
        # Assign the calculated running average to the missing cell
        project_df.at[index, 'Cost'] = running_avg
        
    else:
        # If the cost is present, adding it to our running total sum
        total_cost_sum += current_cost
        # Incrementing the count of valid numbers encountered
        valid_cost_count += 1

# Overwrite the project.csv file with the updated, fully imputed data
project_df.to_csv('project.csv', index=False)

# Displaying the updated dataframe directly in the notebook output
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+06  Finished

In [16]:
####Task 3 : Replacing column "Name" from Employee dataframe with two new columns "First Name" and "Last Name"####
# Importing pandas
import pandas as pd

# Loading the employee dataset created in Task 1
employee_df = pd.read_csv('employee.csv')

# Splitting the 'Name' column at the space character into two temporary series
# expand=True ensures the output is a dataframe with two distinct columns
split_names = employee_df['Name'].str.split(' ', expand=True)

# Inserting 'First Name' right after the 'ID' column
employee_df.insert(1, 'First Name', split_names[0])

# Inserting 'Last Name' right after 'First Name'
employee_df.insert(2, 'Last Name', split_names[1])

# Droping the original 'Name' column
employee_df.drop(columns=['Name'], inplace=True)

# Saving the updated dataset back to the employee.csv file
employee_df.to_csv('employee.csv', index=False)

# Displaying the updated dataframe
employee_df

     ID First Name  Last Name Gender     City  Age
0  A001       John      Alter      M    Paris   25
1  A002      Alice  Luxumberg      F   London   27
2  A003        Tom  Sabestine      M   Berlin   29
3  A004       Nina      Adgra      F  Newyork   31
4  A005        Amy      Johny      F   Madrid   30

In [22]:
####Task 4 : Joining all dataframes into one as a "Final"####
# Import pandas for merging operations
import pandas as pd

# Loading all three datasets
emp_df = pd.read_csv('employee.csv')
sen_df = pd.read_csv('seniority.csv')
proj_df = pd.read_csv('project.csv')

# Merging employee profiles with seniority rankings using the unique 'ID' column
# Using inner join to ensure only matching records are fetched from both datasets
merged_df_temp = pd.merge(emp_df, sen_df, on='ID', how='inner')

# Merging the intermediate dataframe with the project tracking details on 'ID'
# This creates the final unified dataset containing all information
final_df = pd.merge(merged_df_temp, proj_df, on='ID', how='inner')

# Save the final combined dataset to a new CSV file for future tasks
final_df.to_csv('Final.csv', index=False)

# Display the final dataset to confirm all columns are joined properly
final_df

,ID,First Name,Last Name,Gender,City,Age,Designation Level,Project,Cost,Status
0,A001,John,Alter,M,Paris,25,2,Project 1,1.002000e+06,Finished
1,A001,John,Alter,M,Paris,25,2,Project 9,2.061714e+06,Ongoing
2,A001,John,Alter,M,Paris,25,2,Project 11,2.000000e+06,Failed
3,A002,Alice,Luxumberg,F,London,27,2,Project 2,2.000000e+06,Ongoing
4,A002,Alice,Luxumberg,F,London,27,2,Project 6,6.800000e+05,Failed
5,A003,Tom,Sabestine,M,Berlin,29,3,Project 3,4.500000e+06,Finished
6,A003,Tom,Sabestine,M,Berlin,29,3,Project 8,3.500000e+05,Failed
7,A003,Tom,Sabestine,M,Berlin,29,3,Project 10,3.000000e+05,Finished
8,A004,Nina,Adgra,F,Newyork,31,2,Project 4,5.500000e+06,Ongoing
9,A004,Nina,Adgra,F,Newyork,31,2,Project 12,1.000000e+06,Ongoing
10,A004,Nina,Adgra,F,Newyork,31,2,Project 13,3.000000e+06,Finished
11,A005,Amy,Johny,F,Madrid,30,3,Project 5,3.250500e+06,Finished
12,A005,Amy,Johny,F,Madrid,30,3,Project 7,4.000000e+05,Finished
13,A005,Amy,Johny,F,Madrid,30,3,Project 14,2.000000e+06,Finished

In [24]:
####Task 5: Adding a 5% bonus column for employees who have finshed the projects. ####
import pandas as pd

# Loading the Final dataset produced in Task 4
final_df = pd.read_csv('Final.csv')

# Initializing a bonus amount list to calculate and keep track of bonus earned
calculated_bonuses = []

# Iterating step-by-step through every row of the final table
for step in range(len(final_df)):
    # Retrieving the project status and project budget for current row
    current_project_status = final_df.at[step, 'Status']
    project_cost = final_df.at[step, 'Cost']
    
    # Applying logic: Only 'Finished' projects qualify for financial payouts
    if current_project_status == 'Finished':
        # Allocating 5% of the total project budget as a bonus value
        bonus_amount = project_cost * 0.05
    else:
        # No reward for incomplete or failed projects
        bonus_amount = 0.0
        
    # Adding the evaluated figure directly to a tracking list
    calculated_bonuses.append(bonus_amount)

# Inserting Bonus retrieved into the final table under a "Bonus" column
final_df['Bonus'] = calculated_bonuses

# Overwriting the unified csv file with update one
final_df.to_csv('Final.csv', index=False)

# Displaying the modified final table
final_df

,ID,First Name,Last Name,Gender,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,John,Alter,M,Paris,25,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,John,Alter,M,Paris,25,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,John,Alter,M,Paris,25,2,Project 11,2.000000e+06,Failed,0.0
3,A002,Alice,Luxumberg,F,London,27,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,Alice,Luxumberg,F,London,27,2,Project 6,6.800000e+05,Failed,0.0
5,A003,Tom,Sabestine,M,Berlin,29,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Tom,Sabestine,M,Berlin,29,3,Project 8,3.500000e+05,Failed,0.0
7,A003,Tom,Sabestine,M,Berlin,29,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Nina,Adgra,F,Newyork,31,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Nina,Adgra,F,Newyork,31,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Nina,Adgra,F,Newyork,31,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Amy,Johny,F,Madrid,30,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Amy,Johny,F,Madrid,30,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Amy,Johny,F,Madrid,30,3,Project 14,2.000000e+06,Finished,100000.0

In [25]:
####Task 6: Demoting employees with Failed Project status by 1 and deleting record of employees who have reached level >4####
# Importing pandas
import pandas as pd

# Loading the final dataframe
final_df = pd.read_csv('Final.csv')

# Updating 'Designation Level' for failed projects by 1
# .loc locates rows where Status is 'Failed' and increases the level directly
final_df.loc[final_df['Status'] == 'Failed', 'Designation Level'] += 1

# Filtering the dataframe to keep records where Designation Level is 4 or below
# This drops any employee row whose level is strictly above 4
final_df = final_df[final_df['Designation Level'] <= 4]

# Overwriting the final dataset with these level and employee changes
final_df.to_csv('final_merged.csv', index=False)

# Displaying the modified final table
final_df

,ID,First Name,Last Name,Gender,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,John,Alter,M,Paris,25,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,John,Alter,M,Paris,25,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,John,Alter,M,Paris,25,3,Project 11,2.000000e+06,Failed,0.0
3,A002,Alice,Luxumberg,F,London,27,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,Alice,Luxumberg,F,London,27,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Tom,Sabestine,M,Berlin,29,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Tom,Sabestine,M,Berlin,29,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Tom,Sabestine,M,Berlin,29,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Nina,Adgra,F,Newyork,31,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Nina,Adgra,F,Newyork,31,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Nina,Adgra,F,Newyork,31,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Amy,Johny,F,Madrid,30,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Amy,Johny,F,Madrid,30,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Amy,Johny,F,Madrid,30,3,Project 14,2.000000e+06,Finished,100000.0

In [26]:
####Task 7 : Adding titles based on Gender in First Name column and deleting gender column####
# Importing pandas
import pandas as pd

# Loading the current final table
final_df = pd.read_csv('Final.csv')

# Using a loop to iterate through every row index
for i in range(len(final_df)):
    # Extract the gender character string for the current row
    gender_type = final_df.at[i, 'Gender']
    
    # Check if the individual is male
    if gender_type == 'M':
        # Attach the 'Mr.' prefix 
        final_df.at[i, 'First Name'] = 'Mr. ' + str(final_df.at[i, 'First Name'])
    # Check if the individual is female
    elif gender_type == 'F':
        # Attach the 'Mrs.' prefix
        final_df.at[i, 'First Name'] = 'Mrs. ' + str(final_df.at[i, 'First Name'])

# Droping the 'Gender' column
final_df.drop(columns=['Gender'], inplace=True)

# Overwriting the final dataset file with the newly added titles
final_df.to_csv('Final.csv', index=False)

# Displaying the final dataset
final_df

,ID,First Name,Last Name,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,Mr. John,Alter,Paris,25,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Mr. John,Alter,Paris,25,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Mr. John,Alter,Paris,25,2,Project 11,2.000000e+06,Failed,0.0
3,A002,Mrs. Alice,Luxumberg,London,27,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,Mrs. Alice,Luxumberg,London,27,2,Project 6,6.800000e+05,Failed,0.0
5,A003,Mr. Tom,Sabestine,Berlin,29,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Mr. Tom,Sabestine,Berlin,29,3,Project 8,3.500000e+05,Failed,0.0
7,A003,Mr. Tom,Sabestine,Berlin,29,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Mrs. Nina,Adgra,Newyork,31,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Mrs. Nina,Adgra,Newyork,31,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Mrs. Nina,Adgra,Newyork,31,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Mrs. Amy,Johny,Madrid,30,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Mrs. Amy,Johny,Madrid,30,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Mrs. Amy,Johny,Madrid,30,3,Project 14,2.000000e+06,Finished,100000.0

In [27]:
####Task 8 : Promoting Employees by 1 having age more than 29 using IF####
# Importing pandas
import pandas as pd

# Loading the current final table
final_df = pd.read_csv('Final.csv')

# Looping through every index position of the table
for position in range(len(final_df)):
    # Extracting the numerical age value for current employee
    employee_age = final_df.at[position, 'Age']
    
    # Evaluating if the employees's age is more than 29
    if employee_age > 29:
        # Increasing the designation level by 1
        final_df.at[position, 'Designation Level'] += 1

# Overwriting the final dataset file with promotions
final_df.to_csv('Final.csv', index=False)

# Displaying the final dataset
final_df

,ID,First Name,Last Name,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,Mr. John,Alter,Paris,25,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Mr. John,Alter,Paris,25,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Mr. John,Alter,Paris,25,2,Project 11,2.000000e+06,Failed,0.0
3,A002,Mrs. Alice,Luxumberg,London,27,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,Mrs. Alice,Luxumberg,London,27,2,Project 6,6.800000e+05,Failed,0.0
5,A003,Mr. Tom,Sabestine,Berlin,29,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Mr. Tom,Sabestine,Berlin,29,3,Project 8,3.500000e+05,Failed,0.0
7,A003,Mr. Tom,Sabestine,Berlin,29,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Mrs. Nina,Adgra,Newyork,31,3,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Mrs. Nina,Adgra,Newyork,31,3,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Mrs. Nina,Adgra,Newyork,31,3,Project 13,3.000000e+06,Finished,150000.0
11,A005,Mrs. Amy,Johny,Madrid,30,4,Project 5,3.250500e+06,Finished,162525.0
12,A005,Mrs. Amy,Johny,Madrid,30,4,Project 7,4.000000e+05,Finished,20000.0
13,A005,Mrs. Amy,Johny,Madrid,30,4,Project 14,2.000000e+06,Finished,100000.0

In [34]:
#### Task 9 : Creating a new table TotalProjCost with columns ID, First Name and Total Cost ###
# Importing pandas
import pandas as pd

# Loading the current final table
final_df = pd.read_csv('Final.csv')

# Grouping data by ID and First Name, then adding the 'Cost' column for each group
grouped_df = final_df.groupby(['ID', 'First Name'], as_index=False)['Cost'].sum()

# Creating the final new dataframe "TotalProjCost" with columns ID, First Name and Total Cost
# Renaming the calculated 'Cost' column to 'Total cost'
TotalProjCost = grouped_df.rename(columns={'Cost': 'Total cost'})

# Saving this newly created aggregated dataframe into a separate CSV file
TotalProjCost.to_csv('TotalProjCost.csv', index=False)

# Displaying the new TotalProjCost dataframe
TotalProjCost

     ID  First Name    Total cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  5.650500e+06

In [37]:
#### Task 10 : Printing all employee details with city name containing letter "o". ####
# Importing pandas
import pandas as pd

# Loading the current final table
final_df = pd.read_csv('Final.csv')

# Using string analysis to check if city name contains the letter 'o'
# case=False : To avoid case sensitivity
# na=False : To avoid any random/ unexpected fields
city_filter = final_df['City'].str.contains('o', case=False, na=False)

# Extracting records that matched the criteria
filtered_cities_df = final_df[city_filter]

# Saving the filtered data
filtered_cities_df.to_csv('FilteredCities.csv', index=False)

# Displaying the filtered employee dataset
filtered_cities_df

,ID,First Name,Last Name,City,Age,Designation Level,Project,Cost,Status,Bonus
3,A002,Mrs. Alice,Luxumberg,London,27,2,Project 2,2000000.0,Ongoing,0.0
4,A002,Mrs. Alice,Luxumberg,London,27,2,Project 6,680000.0,Failed,0.0
8,A004,Mrs. Nina,Adgra,Newyork,31,3,Project 4,5500000.0,Ongoing,0.0
9,A004,Mrs. Nina,Adgra,Newyork,31,3,Project 12,1000000.0,Ongoing,0.0
10,A004,Mrs. Nina,Adgra,Newyork,31,3,Project 13,3000000.0,Finished,150000.0